name: Deploy Moh Agus CV

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  envs: DATABASE_URL

                  script: |
                      set -e

                      echo "===== DEBUG ====="
                      whoami
                      echo $HOME
                      echo $PATH
                      which bun || true
                      /home/mohagus/.bun/bin/bun --version

                      echo "📂 Enter project directory"
                      cd /var/www/mycv

                      echo "⬇️ Pull latest code"
                      git fetch origin
                      git reset --hard origin/master

                      echo "📦 Install dependencies"
                      /home/mohagus/.bun/bin/bun install

                      echo "🗄️ Generate Prisma client"
                      /home/mohagus/.bun/bin/bun x prisma generate

                      echo "🗄️ Run database migrations"
                      /home/mohagus/.bun/bin/bun x prisma migrate deploy

                      echo "🌱 Seed database"
                      /home/mohagus/.bun/bin/bun run prisma:seed

                      echo "🏗️ Build project"
                      /home/mohagus/.bun/bin/bun run build

                      echo "🔄 Restart service"
                      sudo systemctl restart mycv

                      echo "✅ Check service status"
                      systemctl is-active mycv

